#pragma config(Sensor, S1,     LeftLight,      sensorEV3_Color)
#pragma config(Sensor, S2,     RightLight,     sensorEV3_Color)
#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//SensorValue[LeftLight]
	//SensorValue[RightLight]
}
